In [1]:
import json
import matplotlib.pyplot as plt

from src.data_processing.data_loader import data_loader
import src.training.training_utils as training_utils
# from src.results.main import evaluate
# import src.visualisation.main as vis_main


In [2]:
with open("src/training/run_config.json", "r") as f:
    run_config = json.load(f)
    f.close()

# Extract info
data_config = run_config["data_config"]
model_config = run_config["model_config"]
training_config = run_config["training_config"]

In [3]:
print(run_config)

{'data_config': {'data_name': 'MIMIC', 'target_window': 48, 'feat_set': 'vit-sta', 'time_range': [0, 10], 'train_test_ratio': 0.6, 'train_val_ratio': 0.4, 'seed': 2323}, 'model_config': {'model_name': 'DirVRNN', 'latent_size': 10, 'gate_layers': 2, 'gate_nodes': 20, 'feat_extr_layers': 2, 'feat_extr_nodes': 20, 'num_clus': 6}, 'training_config': {'lr': 0.001, 'epochs': 5, 'bs': 128}}


In [4]:
from importlib import reload
import src.data_processing.data_loader as loader
reload(loader)

<module 'src.data_processing.data_loader' from 'c:\\Users\\hruia\\PycharmProjects\\VarPhenClustering\\src\\data_processing\\data_loader.py'>

In [ ]:
data_info = loader.data_loader(**data_config);

In [187]:
from src.models.Dir_VRNN import Dir_VRNN_train as model_train
from src.models.Dir_VRNN import model as model
from src.models.Dir_VRNN import Dir_VRNN_utils as model_utils

reload(model_train);
reload(model);
reload(model_utils);

run_config["training_config"]["bs"] = 128
run_config["training_config"]["epochs"] = 20
run_config["model_config"]["num_clus"] = 3
model = model_train.DirVRNN(data_info = data_info, model_config=model_config, training_config=training_config);

In [9]:
import src.models.Dir_VRNN.model as FileModel
reload(FileModel)



X_train, X_val, X_test = data_info["X"]
y_train, y_val, y_test = data_info["y"]

# Define parameters
i_size = X_train.shape[-1]
o_size = y_train.shape[-1]
w_size = 3
model = FileModel.BaseModel(i_size =i_size, o_size=o_size, w_size=w_size, K=6, l_size=64, gate_hidden=1, gate_hidden_n=30)

In [189]:
# Prepare experiment
import torch
from torch.utils.data import DataLoader, TensorDataset

# Compute dimensionality of input and output
input_size = X_train.shape[-1]
outcome_size = y_train.shape[-1]
batch_size=32

# Prepare data for training
train_dataset = TensorDataset(torch.from_numpy(X_train), torch.from_numpy(y_train))
val_dataset = TensorDataset(torch.from_numpy(X_val), torch.from_numpy(y_val))

self.train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
self.val_loader = DataLoader(val_dataset, batch_size=X_val.shape[0])

# Prepare data for evaluating
test_dataset = TensorDataset(torch.from_numpy(X_test), torch.from_numpy(y_test))
self.test_loader = DataLoader(test_dataset, batch_size=X_test.shape[0])


Train epoch: 1   [1837264.41912 - 100%]
Val epoch: 1   [1312438.37500 - 0%]
Train epoch: 2   [774340.64338 - 100%]
Val epoch: 2   [95147.15625 - 0%]
Train epoch: 3   [16349.21591 - 100%]
Val epoch: 3   [-423.29688 - 0%]
Train epoch: 4   [-430.82109 - 100%]
Val epoch: 4   [-439.46552 - 0%]
Train epoch: 5   [-446.51093 - 100%]
Val epoch: 5   [-455.92923 - 0%]
Train epoch: 6   [-478.51230 - 100%]
Val epoch: 6   [-578.17712 - 0%]
Train epoch: 7   [-621.24868 - 100%]
Val epoch: 7   [-642.68951 - 0%]
Train epoch: 8   [-650.71106 - 100%]
Val epoch: 8   [-658.13068 - 0%]
Train epoch: 9   [-663.30345 - 100%]
Val epoch: 9   [-667.90851 - 0%]
Train epoch: 10   [-671.20017 - 100%]
Val epoch: 10   [-674.07709 - 0%]
Train epoch: 11   [-675.67582 - 100%]
Val epoch: 11   [-676.95667 - 0%]
Train epoch: 12   [-677.45951 - 100%]
Val epoch: 12   [-677.80994 - 0%]
Train epoch: 13   [-678.00172 - 100%]
Val epoch: 13   [-678.22363 - 0%]
Train epoch: 14   [-678.41031 - 100%]
Val epoch: 14   [-678.57233 - 0%]


In [169]:
 
    
# Predict model
X_test, y_test = data_info["X"][-1], data_info["y"][-1]
history = model.predict(X_test, y_test)
     
# Print available keys
print(history.keys())
             
                 
                     
                         
                             
                                 
                                     
                                         
                                             
                                                 
                                                    

Test: [-1133.16125 - 0%]
dict_keys(['alpha_prior', 'alpha_enc', 'est_pi', 'est_cluster_means', 'est_outcomes', 'est_gen_mean', 'est_gen_data', 'cell_state', 'pred_loss', 'y_pred', 'X', 'y'])


In [171]:
history["est_pi"].shape

torch.Size([3565, 10, 6])

In [179]:
test = history["est_pi"][:, -1, :]
clus_one_hot = [torch.argmax(test, axis=1).detach().numpy()]

In [186]:
np.matmul(np.transpose(clus_one_hot), y_test)

array([[  1.,  92., 608.,  91.],
       [  2.,  94., 540.,  62.],
       [  0.,  89., 530.,  72.],
       [  0.,   0.,   0.,   0.],
       [  1.,  98., 522.,  79.],
       [  0.,  80., 514.,  90.]])

In [42]:
import numpy as np
history["alpha_enc"][0, :, :] / torch.sum(history["alpha_enc"][0, :, :], dim=-1, keepdims=True)

tensor([[0.3198, 0.6802],
        [0.3029, 0.6971],
        [0.3031, 0.6969],
        [0.3030, 0.6970],
        [0.3031, 0.6969],
        [0.3031, 0.6969],
        [0.3031, 0.6969],
        [0.3030, 0.6970],
        [0.3030, 0.6970],
        [0.3030, 0.6970]], grad_fn=<DivBackward0>)

In [43]:
history["alpha_enc"][101, :, :] / torch.sum(history["alpha_enc"][101, :, :], dim=-1, keepdims=True)

tensor([[0.3194, 0.6806],
        [0.3027, 0.6973],
        [0.3031, 0.6969],
        [0.3030, 0.6970],
        [0.3031, 0.6969],
        [0.3032, 0.6968],
        [0.3020, 0.6980],
        [0.3020, 0.6980],
        [0.3020, 0.6980],
        [0.3020, 0.6980]], grad_fn=<DivBackward0>)

In [38]:
import torch
torch.min(history["est_pi"], dim=1)

torch.return_types.min(
values=tensor([[0.3029, 0.6802],
        [0.3025, 0.6785],
        [0.3039, 0.6778],
        ...,
        [0.3020, 0.6792],
        [0.3020, 0.6800],
        [0.3014, 0.6812]], grad_fn=<MinBackward0>),
indices=tensor([[1, 0],
        [3, 0],
        [1, 0],
        ...,
        [8, 0],
        [8, 0],
        [8, 0]]))